# Sends destination waypoint from CoordinateInput GUI to waypoint_manager and
# returns the NE distances from origin in mapviz.
float32 lat
float32 lon
float32 origin_lat
float32 origin_lon
---
float32 dist_N
float32 dist_E
