#Params are in m and radians
/**:
  ros__parameters:
    path_waypoint_distance_tolerance: 4.0
    distance_tolerance: 1.0
    obj_distance_tolerance: 1.5 #TODO: Tune
    abort_distance_tolerance: 7.0
    aruco_distance_tolerance: 2.0
    hex_search_radius: 10.0
    navigate_speed: 10.0
    object_speed: 3.0
    aruco_speed: 3.0
    spin_speed: 0.5
    object_alpha_lpf: 0.20
    obj_enable_distance: 30.0
    obj_navigate_delay_time: 2.0
    aruco_enable_distance: 30.0
    aruco_alpha_lpf: 0.5
    spin_step_size: 0.6981
    spin_delay_time: 17.0     # Time in seconds for the rover to spin before moving to search points
    wrong_aruco_backup_distance: 7.0
    wrong_aruco_backup_spin_speed: 15.0
    hex_seach_angle_difference: 50.0

    waypoint_distance: 10.0
    elevation_cost: 200.0 # How much elevation affects the cost of the computed AStar path
    # The below distance in meters creates angle with an 1 meter AStar step on the xy plane
    # For example, if you set the distance to 0.7, the maximum traversable angle is tan^-1(0.7/1.0) = 35 degrees
    elevation_limit: 0.35 # The maximum allowable elevation difference in the AStar planner to be considered traversable
    spiral_inital_radius: 4.0  # Initial Radius for first spiral point (Meters)
    spiral_growth_factor: 1.0  # Growth between each point  (Meters)
    spiral_step_size: 45.0    # Spiral Angle step size (degrees)
    roll_cost: 1.0 # How much roll affects the cost of the computed AStar path
    # The below distance in meters creates angle with two 1 meter AStar steps on the xy plane
    # For example, if you set the distance to 0.7, the maximum traversable angle is tan^-1(1.4/2.0) = 35 degrees
    roll_limit: 1.4 # The maximum allowable roll difference in the AStar planner to be considered traversable


fiducial_data:
  ros__parameters:
    simulation: false     #Run in simulation mode
    target_ar_tag_id: -1  #Target AR Tag ID