# Created by Nelson Durrant, Oct 2024

services:
  autonomy_ros2:
    image: byuawesomerover/autonomy_ros2:latest
    container_name: autonomy_ros2
    build: .
    user: marsrover
    network_mode: host
    privileged: true
    volumes:
      - ../mars_ws:/home/marsrover/mars_ws
      - ../scripts:/home/marsrover/scripts
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /var/run/docker.sock:/var/run/docker.sock # Required for docker in docker
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm
    command: ["/bin/bash", "-c", "/home/marsrover/scripts/entrypoint.sh", "/bin/bash"]
