# Receieved by src/path_planning/src/a_star.py
#
# This message file allows a node to send a set of waypoints to the path_planning
# module. The path planning module will then plan a path between all of the waypoints.
# Note that the two arrays below are paired. The value at index 0 of north_coords is
# combined with the value at index 0 of east_coords to generate the first waypoint.

float64 latitude    # latitude
float64 longitude    # longitude
string tag_id #aruco tag id
