#This message is used to grab feedback from the arduino
#each motor will have a speed, amps, and error status

uint8 right_front_speed
uint8 right_front_amps
uint8 right_front_error

uint8 right_middle_speed
uint8 right_middle_amps
uint8 right_middle_error

uint8 right_rear_speed
uint8 right_rear_amps
uint8 right_rear_error

uint8 left_front_speed
uint8 left_front_amps
uint8 left_front_error

uint8 left_middle_speed
uint8 left_middle_amps
uint8 left_middle_error

uint8 left_rear_speed
uint8 left_rear_amps
uint8 left_rear_error
