float32 north       # base frame cartesian north position (m)
float32 west        # base frame cartesian west position (m)
float32 u           # body frame longitudinal velocity (m/s)
float32 v           # body frame lateral velocity (m/s)
float32 theta       # heading (rad) (from north) TODO is this towards west or towards east???
float32 omega       # angular rate (rad/s)
float32 psidot_L    # left wheel angular rate (rad/s)
float32 psidot_R    # right wheel angular rate (rad/s)