# Received by autonomy/src/state_machine_new.py
# 
# Contains a list of AutonomyTaskInfo messages.
# 
# The autonomy gui uses this message to send all of the intermediary 
# latitude and longitude points corresponding to the best path 
# topographically as planned by the path_planner node.

AutonomyTaskInfo[] task_list
---
bool success
string message