# Received by autonomy/src/state_machine_new.py
# 
# Contains a list of AutonomyTaskInfo messages. The purpose is to allow the 
# GUI to send a list of all waypoints to the rover at the same time.

AutonomyTaskInfo[] task_list
---
bool success
string message