/**:
  ros__parameters:
    height_threshold: 0.3
    slope_threshold: 15.0
    voxel_grid_size: .1
    ground_distance_threshold: .05
    bounding_box_start_point: [-0.5, 0.0, 0.5]
    bounding_box_length: 5.0
    bounding_box_width: 3.0
    bounding_box_height: 3.0
    bounding_box_height_ditch: 3.0
    epsilon_clustering_density: 0.4
    min_points_to_cluster: 50
    verbose: False
