pcl_processor:
  ros__parameters:
    # Parameters for bounding box 
    # X is forward, Y is left, Z is up
    # TODO should figure out a way to angle the bounding box??
    bbox_min_x: 0.5
    bbox_max_x:  2.5
    bbox_min_y: -0.45
    bbox_max_y:  0.45
    bbox_min_z: -0.0
    bbox_max_z:  1.6
    bbox_max_y_left: 2.0
    bbox_min_y_right: -2.0

    # Publishh cropped point cloud and bounding box
    verbose_publishing: false