# Created by Nelson Durrant, Nov 2024

name: Docker Image CI (autonomy_ros2)

on:
  push:
    branches: [ "main" ]
    paths: 
      - "docker/Dockerfile"

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v6
      with:
       context: "{{defaultContext}}:docker"
       platforms: linux/amd64 
       # As of Feb 2025, a QEMU error occurs when you add linux/arm64 above
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/autonomy_ros2:latest
